name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    strategy:
      matrix:
        include:
          # Windows Server 2016 + Visual Studio 2017
          - name: "Windows Server 2016 + Visual Studio 2017"
            os: windows-2016
          # Windows Server 2019 + Visual Studio 2019
          - name: "Windows Server 2019 + Visual Studio 2019"
            os: windows-2019

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Configure Build
      run: mkdir build && cd build && cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=Release -DBGFX_BUILD_EXAMPLES=OFF -DBGFX_BUILD_TOOLS=ON -DBGFX_INSTALL=ON ..
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build
      run: cd build && MSBuild.exe Cubby.sln /p:Configuration=Release
    - name: Run Unit Test
      run: /a/Cubby/Cubby/build/bin/Release/UnitTests.exe